# Generated by Django 4.2.26 on 2025-11-19 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_asset_maintenance_cost_forecast_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('scenario_type', models.CharField(choices=[('revenue_change', 'Revenue Change'), ('expense_reduction', 'Expense Reduction'), ('investment_impact', 'Investment Impact')], max_length=30)),
                ('description', models.TextField()),
                ('input_parameters', models.JSONField(help_text='Input parameters for the scenario')),
                ('predicted_outcomes', models.JSONField(help_text='Predicted outcomes from the scenario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_date', models.DateField()),
                ('period_months', models.IntegerField(default=12, help_text='Projection period in months')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('expense_optimization', 'Expense Optimization'), ('investment_opportunity', 'Investment Opportunity'), ('budget_adjustment', 'Budget Adjustment'), ('category_suggestion', 'Category Suggestion')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('suggested_action', models.TextField()),
                ('impact_estimate', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated financial impact', max_digits=15, null=True)),
                ('confidence_score', models.FloatField(default=0.0, help_text='Confidence score between 0.0 and 1.0')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_applied', models.BooleanField(default=False)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations_applied', to=settings.AUTH_USER_MODEL)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('related_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.asset')),
                ('related_budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.budget')),
                ('related_investment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.investment')),
                ('related_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PredictiveModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('model_type', models.CharField(choices=[('cash_flow_forecast', 'Cash Flow Forecast'), ('revenue_prediction', 'Revenue Prediction'), ('expense_anomaly', 'Expense Anomaly Detection'), ('investment_roi', 'Investment ROI Prediction')], max_length=30)),
                ('version', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('training_data_start', models.DateField()),
                ('training_data_end', models.DateField()),
                ('accuracy_score', models.FloatField(blank=True, null=True)),
                ('feature_columns', models.JSONField(help_text='List of features used in the model')),
                ('algorithm_used', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('model_name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='FinancialForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_type', models.CharField(choices=[('cash_flow', 'Cash Flow'), ('revenue', 'Revenue'), ('expense', 'Expense'), ('investment', 'Investment Return')], max_length=20)),
                ('predicted_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('confidence_interval_low', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('confidence_interval_high', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('prediction_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_used', models.CharField(help_text='Algorithm/model used for prediction', max_length=100)),
                ('training_period_start', models.DateField()),
                ('training_period_end', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-prediction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnomalyDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_type', models.CharField(choices=[('expense_spike', 'Expense Spike'), ('unusual_amount', 'Unusual Amount'), ('category_deviation', 'Category Deviation'), ('frequency_change', 'Frequency Change')], max_length=30)),
                ('detected_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('expected_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('severity', models.IntegerField(default=1, help_text='1=Low, 2=Medium, 3=High')),
                ('description', models.TextField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.transaction')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
    ]
