# Generated by Django 4.2.26 on 2025-11-19 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='maintenance_cost_forecast',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Predicted future maintenance costs', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='predicted_maintenance_date',
            field=models.DateField(blank=True, help_text='Predicted next maintenance date', null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='predicted_roi',
            field=models.FloatField(default=0.0, help_text='AI/ML predicted ROI for this investment'),
        ),
        migrations.AddField(
            model_name='investment',
            name='predicted_value_12m',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Predicted value in 12 months', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='risk_assessment_updated',
            field=models.DateTimeField(blank=True, help_text='Last date when risk was assessed by ML model', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='ml_confidence_score',
            field=models.FloatField(default=0.0, help_text='Confidence score for ML-based category prediction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='ml_predicted_category',
            field=models.ForeignKey(blank=True, help_text='Machine learning predicted category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ml_predicted_transactions', to='app.category'),
        ),
    ]
