# Generated by Django 4.2.26 on 2025-11-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_asset_maintenance_cost_forecast_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='depreciation_method',
            field=models.CharField(choices=[('straight_line', 'Straight Line'), ('declining_balance', 'Declining Balance')], default='straight_line', max_length=20),
        ),
    ]
